### ISSUE TITLE
Doesn’t work with `babel-plugin-react-intl@7.5.0`

### ISSUE THREAD

**Issue by lensbart** [akameco/babel-plugin-react-intl-auto#128]
Downgrading to `babel-plugin-react-intl@^7.4.0` fixes the issue

**Comment by Hydraz320** [comment]
Same problem.

**Comment by Hydraz320** [comment]
> Downgrading to `babel-plugin-react-intl@^7.4.0` fixes the issue

Hi, I still have problem with `babel-plugin-react-intl@~7.4.0`. It seems that the `assertObjectExpression` method in source code throw an error.

**Comment by akameco** [comment]
Thank you for reporting. What kind of error occurs in what case?

**Comment by Hydraz320** [comment]
My bad. The order of babel plugins is wrong.

**Comment by Reeywhaar** [comment]
Have no problem with 7.5.4

**Comment by akameco** [comment]
Thank you for your reply.
Open it again if that matters.
