### ISSUE TITLE
Allow Id value to only include export name?

### ISSUE THREAD

**Issue by adam-26** [akameco/babel-plugin-react-intl-auto#13]
Hi,

Nice library. I would like to configure the options so that the generated id value **only** includes the `exportName`, resulting in much shorted id values. I'm happy to do the work if you'll accept such a feature as a PR?

I was thinking that this could easily by achieved by allowing the `removePrefix` option to also allow a value of `true` when `includeExportName` is also true. Example .babelrc:

```js
{
  "plugins": [
    ["react-intl-auto", {
      "removePrefix": true,
      "includeExportName": true
    }]
  ]
}
```

Using the example from the readme, this would result in:

```js
// before
export const test = defineMessages({
  hello: 'hello {name}',
})

// after
export const test = defineMessages({
  hello: {
    id: 'test.hello',
    defaultMessage: 'hello {name}',
  },
})
```

You might have an preferred alternative, or prefer to add a new property to allow this? Let me know what you think.

Cheers, Adam.

**Comment by akameco** [comment]
Thanks for reporting the issue 👍 

Good point.
I agree with you.
I am looking forward to your PR 😀
