### ISSUE TITLE
ID didn't pass to FormattedMessage

### ISSUE THREAD

**Issue by hurvajs77** [akameco/babel-plugin-react-intl-auto#133]
* version: 3.3.0
* `node` version: v14.1.0
* `npm` (or `yarn`) version: yarn v1.22.4

**Do you want to request a _feature_ or report a _bug_?:**
I use clean React app (via create-react-app), extraction of the messages works, but if I try use it `got Error: [React Intl] An `id` must be provided to format a message.`

**What is the current behavior?:**
My .babelrc
```
{
  "presets": [ "@babel/preset-env", "@babel/preset-react", "@babel/preset-flow"],
  "plugins": [["react-intl-auto", { "removePrefix": "src.Components" }]]
}
```

I use same message files as in the example.
```
import { defineMessages } from 'react-intl';

export default defineMessages({ en: 'ABBR_EN' });
```

and in the component: 
```
<a href="#" onClick={handleClick('en')}>
    <FormattedMessage {...messages.en} />
</a>
```

**What is the expected behavior?:**
Pass `id` and `defaultMessage` into `FormattedMessage` component

**Comment by hurvajs77** [comment]
closing, not supported repository, unsupported pure ReactApp based on create-react-app

**Comment by arvinsim** [comment]
> closing, not supported repository, unsupported pure ReactApp based on create-react-app

Does this mean that `create-react-app` projects will not work with this plugin?
