### ISSUE TITLE
Hash Id values to reduce size of translation files

### ISSUE THREAD

**Issue by adam-26** [akameco/babel-plugin-react-intl-auto#14]
To enable consistently short id values to be generated, provide an option that will hash each message id.

This could be designed to support multiple algorithms, but initially I suggest the `murmur3` algorithm due to its low collision rate and 32bit output. An example configuration:

```js
{
  "plugins": [
    ["react-intl-auto", {
      "idHash": "murmur3",
      ...other config
    }]
  ]
}
```

When used with #13, it allows id hash values to be consistent across builds unless:
1. The object key name is changed in the original javascript message file
2. The variable name used to generate the id value changes

_Id hash values will not change if the file is renamed or moved_, this is good in scenario's where translations have already been performed.

Essentially, its just:
```js
var murmurhashJs = require("murmurhash-js");

// Function to converta 32 bit integer to an array
// https://stackoverflow.com/questions/15761790/convert-a-32bit-integer-into-4-bytes-of-data-in-javascript
function toBytesInt32 (num) {
    arr = new ArrayBuffer(4); // an Int32 takes 4 bytes
    view = new DataView(arr);
    view.setUint32(0, num, false); // byteOffset = 0; litteEndian = false
    return arr;
}

// Generate a short hash for each message id value
const idHash = murmurhashJs('message_identifier');
console.log(Buffer.from(toBytesInt32(idHash)).toString('base64'));
```
You can [run that here](https://npm.runkit.com/murmurhash-js) with a quick copy & paste.

Would you accept this as a PR?

Adam.

**Comment by akameco** [comment]
Umm...
I think it complicates key management.
And I don't want to increase options anymore.

However you can create new library for this :)

**Comment by adam-26** [comment]
For anyone looking for a way to reduce the length of the `id` values, and thereby reduce you're bundled application size, you can use [babel-plugin-react-intl-id-hash](https://github.com/adam-26/babel-plugin-react-intl-id-hash) with this plugin.

This reduces the `id` value of each message to 8 characters.

@akameco, not sure if you'd be interested in adding 1 line about this to the readme?

**Comment by akameco** [comment]
Sure.
PR Welcome 😀
