### ISSUE TITLE
Use leading comment as description?

### ISSUE THREAD

**Issue by Ephys** [akameco/babel-plugin-react-intl-auto#18]
Adding descriptions is cumbersome, leading to a diminished use of them.
It would be nice if leading comments were extracted and used as the description.

IN:
```
export default defineMessages({
  // message displayed when credentials are invalid
  errorPassword: 'Invalid Password',

  // message displayed when all is ok
  labelSuccess: {
    defaultMessage: 'Logged in',
  },
});
```

OUT:
```
export default defineMessages({
  errorPassword: {
    id: 'app.view.Login.errorPassword',
    defaultMessage: 'Invalid Password',
    description: 'message displayed when credentials are invalid',
  },
  labelSuccess: {
    id: 'app.view.Login.labelSuccess',
    defaultMessage: 'Logged in',
    description: 'message displayed when all is ok',
  },
});
```

It'd also be great if this was configurable, so we can enable it when generating the various locale files but keep it disabled when building the actual app to reduce the bundle size.

Is this something you'd be interesting in adding? Do you want me to write a PR?

**Comment by akameco** [comment]
@Ephys Thanks for the suggestion. This is a good idea!
I'm looking forward to your PR :)
