### ISSUE TITLE
Options param

### ISSUE THREAD

**Issue by carlgrundberg** [akameco/babel-plugin-react-intl-auto#21]
In your example script you pass _defaultLocale_ as the fourth parameter, but it is an options parameter that has defaultLocale as one of the options.

https://github.com/akameco/babel-plugin-react-intl-auto/blob/dfa13935865449cde102c28ea9c9e917172fd55d/examples/with-flow/scripts/extract-intl-messages.js#L9

This works:

`extractReactIntlMessages(locales, pattern, buildDir, { defaultLocale });`

**Comment by akameco** [comment]
Thank you @carlgrundberg 👍 
Would you write a PR?
