### ISSUE TITLE
Support React Components

### ISSUE THREAD

**Issue by grebenyuksv-preply** [akameco/babel-plugin-react-intl-auto#27]
Dear maintainers, thanks for your great plugin. I'm thinking of using it in a mid-size project. Do you have any plans (or maybe is there any ongoing work) to start supporting generating the `id` prop for React components like `<FormattedMessage id="generatedID" />`?

**Comment by akameco** [comment]
No I am not working.
But it is interesting :)
When automatically generating with Component, what do you use to generate id?
Are there any ideas?
