### ISSUE TITLE
Inject react-intl-auto to create-react-app doesn't work

### ISSUE THREAD

**Issue by OneStromberg** [akameco/babel-plugin-react-intl-auto#38]
* version: 1.1.0
* `node` version: 8.9.1
* `npm` (or `yarn`) version: 5.7.1

I have a bug according to injection **react-intl-auto** pluging into my `create-react-app` App. I'm using **react-app-rewired** and my config is:

`const { injectBabelPlugin } = require('react-app-rewired');`
`const rewireLess = require('react-app-rewire-less');`

`module.exports = function override(config, env) {`
`  config = injectBabelPlugin(['react-intl-auto', { "removePrefix": "./src/" }], config);`
`  config = rewireLess(config, env);`
`  return config;`
`};`

And I have run-time error with:
**The prop `id` is marked as required in `FormattedMessage`**

I hope I shouldn't do `eject` to user **react-intl-auto**
Thanx for any suggestions!

**Comment by akameco** [comment]
@OneStromberg Thank you for the report.
Could you show me reproduction repository?
