### ISSUE TITLE
Different translation output depending on `filebase` flag while having translation keys duplicated on purpose

### ISSUE THREAD

**Issue by neu5** [akameco/babel-plugin-react-intl-auto#40]
* version: 1.1.0
* `node` version: 8.10.0
* `yarn` version: 1.7.0

**Do you want to request a _feature_ or report a _bug_?:**
Feature

**What is the current behavior?:**
Currently while having default `babel-plugin-react-intl-auto` configuration, like (package.json):
```
  "babel": {
   //    ...
    "plugins": ["react-intl-auto"]
  }
```
If I have the same keys in object in `defineMessages` used in different files, eg.
```
// A.js, B.js
defineMessages({
  hello: 'hello {name}',
  welcome: 'Welcome!',
})
```
While running
`"NODE_ENV=development extract-messages -l=en --flat -o src/translations 'src/**/!(*.test).js'"`

I'll get:
```
{
  "src.containers.hello": "hello {name}",
  "src.containers.welcome": "Welcome!"
}
```
With configuration of a plugin in `package.json` like:
```
  "babel": {
   //    ...
    "plugins": [
        "react-intl-auto", {
            "filebase": true
        }
    ]
  }
```
I'll get:
```
{
  "src.containers.A.hello": "hello {name}",
  "src.containers.A.welcome": "Welcome!",
  "src.containers.B.hello": "hello {name}",
  "src.containers.B.welcome": "Welcome!"
}
```

**What is the expected behavior?:**
I'm not sure but I would expect to either get an error if I have keys duplication or get the keys generated with some hash to be able to distinguish between them.

**Comment by akameco** [comment]
@neu5 It is a good suggestion.
I think it would be nice if there was an error when keys duplication.
Welcome PRs.
