### ISSUE TITLE
Support for <FormattedMessage /> API

### ISSUE THREAD

**Issue by neu5** [akameco/babel-plugin-react-intl-auto#44]
**Do you want to request a _feature_ or report a _bug_?:**
Feature

**What is the current behavior?:**
Currently auto-generated id feature is working only for **defineMessages** API.
If you don't assign `id` to the `<FormattedMessage />` the translation key will be generated by `babel-plugin-react-intl-auto` but `react-intl` will raise an error and break the app because the `id` attribute is required by `react-intl`.

**What is the expected behavior?:**
`babel-plugin-react-intl-auto` should insert the `id` attribute to `<FormattedMessage />` if it's missing similarly as it inserts the `id` to **defineMessages**.

**Comment by akameco** [comment]
Already supported. 
See https://github.com/akameco/babel-plugin-react-intl-auto/pull/31 .
