### ISSUE TITLE
use regex or Array for removePrefix option

### ISSUE THREAD

**Issue by Victorien-Tardif** [akameco/babel-plugin-react-intl-auto#45]
**Feature request: use regex or Array for removePrefix option**
I have messages in different folders and I'd like to remove prefix (which is therefore different for each folder) for all of them.

**What is the current behavior?:**
We can only set a string.

**What is the expected behavior?:**
even `removePrefix: 'regex'`
or `removePrefixes: ['string1', 'string2']`

**Suggested solution:**

**Comment by abeMedia** [comment]
My team also has the requirement of using a regex for the `removePrefix` option. I'd be happy to do a PR if this is something you'd accept @akameco

**Comment by mvestergaard** [comment]
Has anyone gotten this to work?
When i specify a regexp in my .babelrc.js, babel appears to ignore the plugin completely.

**Comment by mvestergaard** [comment]
Nevermind, not sure why it wasn't working. It works after i re-installed my node_modules

**Comment by fsmaia** [comment]
It would be nice to update the README too. I was about to open a new issue about the very same feature :)
