### ISSUE TITLE
Syntax error: [React Intl] `defineMessages()` must be called with an object expression

### ISSUE THREAD

**Issue by 5tormTrooper** [akameco/babel-plugin-react-intl-auto#49]
* `node` version: v10.10.0
* `npm` (or `yarn`) version: 
"babel-plugin-react-intl-auto": "^1.1.1", 
"react-intl": "^2.4.0",
"react-app-rewire-react-intl": "^2.4.0",
"react-app-rewired": "^1.5.2",

**Do you want to request a _feature_ or report a _bug_?:**
Report a bug

**What is the current behavior?:**
`<FormattedMessage />` is generating IDs, but not adding the ID to the <FormattedMessage /> component, and when using the `defineMessages` API, I get an error when compiling.
<img width="350" alt="image 2018-12-04 at 1 28 54 pm" src="https://user-images.githubusercontent.com/4154407/49442133-d7bfef00-f7c8-11e8-9e6e-cc3700076501.png">

<img width="952" alt="image 2018-12-04 at 1 32 24 pm" src="https://user-images.githubusercontent.com/4154407/49442261-42712a80-f7c9-11e8-9e1a-05aee6805226.png">

**What is the expected behavior?:**
As per the documentation, I expect to be able to use defineMessages like so:

<img width="349" alt="image 2018-12-04 at 1 35 35 pm" src="https://user-images.githubusercontent.com/4154407/49442339-85cb9900-f7c9-11e8-89ee-508a96e4ef34.png">

Am I doing something wrong?

I should mention that I'm using react-app-rewired with a config-overrides file to inject Babel plugins without ejecting CRA. This is my config for react-intl-auto:
```
config = injectBabelPlugin(
    ["react-intl-auto", { removePrefix: "src" }],
    config
  );
```

**Comment by Filson14** [comment]
@5tormTrooper You've mentioned problem with `<FormattedMessage />` component, while the error shows incorrect form of the object passed to _defineMessages_. It looks like babel does not tranform your code with **react-intl-auto** OR that plugin tries to run it to late.

**Comment by Filson14** [comment]
Hmm... I may have simillar issue right now, tho :disappointed:

In our project we use **flow** to manage typing. While running dev-server everything is ok (but then I don't run flow check AND run babel). During flow check (on raw source code), it actually throws error (it's not suprising tho). I have a workaround with _defineMessages_ wrapper with //$FlowFixMe, but I'm open to any suggestions how to do it right :wink: 

![image](https://user-images.githubusercontent.com/4540538/51981768-56b56900-2494-11e9-8658-7716076bf08c.png)
