### ISSUE TITLE
/examples/with-flow not working

### ISSUE THREAD

**Issue by 5tormTrooper** [akameco/babel-plugin-react-intl-auto#52]
* version: ^2.4.0
* `node` version: v10.10.0
* `yarn` version: 1.12.3

Reporting a bug.

With a clean pull of the example directory, running `yarn` returns errors, the first of which is: 
```
warning Error running install script for optional dependency: "/Users/Storm/Development/playground/react-intl-auto/node_modules/fsevents: Command failed.
```

The expected behaviour is to run:
```
$ yarn
$ npm link babel-plugin-react-intl-auto
```
and get the example working.

**Comment by akameco** [comment]
@5tormTrooper Thanks for the report. Fixed 👍
