### ISSUE TITLE
Integration issue with extract-react-intl-messages

### ISSUE THREAD

**Issue by urvashi01** [akameco/babel-plugin-react-intl-auto#62]
* version: 1.6.0
* `node` version: 8.12.0
* `npm` (or `yarn`) version: 6.4.1

**Do you want to request a _feature_ or report a _bug_?:**
Report a bug

**What is the current behavior?:**
As per the suggestion in README, I have tried using extract-react-intl-messages for descriptors' extraction. To achieve this, I took the following steps-
1. Run babel on my src directory  (attached babelrc) -
```
{
  "presets": [
    [
      "babel-preset-react-app"
    ]
  ],
  "plugins": [
    [
      "react-intl-auto",
      {
        "removePrefix": true,
        "includeExportName": true
      }
    ]
  ]
}
```
2. Run extract-messages script to get the json.

This fails to extract the labels defined through JSX elements like Formatted message.

Running babel with intl-auto plugin prior to extract script, converts the JSX elements to React.createElement calls. Running extract script after this, intenally invokes babel-plugin-react-intl which only visits JSXOpeningElement and CallExpression nodes. Since, the JSX nodes are already converted to function calls, it misses on these translations.

**What is the expected behavior?:**
It should extract labels from JSX defined descriptors too.

Could you please help point out the steps I am missing or executing the wrong way to achieve this integration?

**Comment by akameco** [comment]
@urvashi01 Still not solved? Please prepare a reproduction repository.
