### ISSUE TITLE
[feature] Injection API support (intl.formatMessage)

### ISSUE THREAD

**Issue by jmarceli** [akameco/babel-plugin-react-intl-auto#66]
Thanks for this plugin and your time spent on its development.

Do you have any plans for adding Injection API support?

Currently, the following code won't be extracted and id won't be autogenerated:

```
intl.formatMessage({ defaultMessage: 'Hello' })
```

As far as I'm aware in babel-plugin-react-intl there is already a PR waiting for a merge with this feature supported (https://github.com/yahoo/babel-plugin-react-intl/pull/165).
I would be happy to help with implementation but I have no experience with Babel plugins development.

**Comment by akameco** [comment]
If that PR is merged, I will implement it.

**Comment by jmarceli** [comment]
Feel free to merge my PR if you find it useful https://github.com/akameco/babel-plugin-react-intl-auto/pull/68, or let me know if there is anything that I should improve.

**Comment by akameco** [comment]
ref #68
