### ISSUE TITLE
Production build failing when using with create-react-app

### ISSUE THREAD

**Issue by liemdo** [akameco/babel-plugin-react-intl-auto#73]
* version:
* `node` version: 12.4.0
* `npm` (or `yarn`) version: 6.9.0

**Do you want to request a _feature_ or report a _bug_?:**
_bug_

**What is the current behavior?:**
I use babel-plugin-react-intl-auto with create-react-app, it works fine using development server. However, when I build the app, I get this error:

TypeError: Cannot read property 'name' of undefined
    at Array.find (<anonymous>)

I used to use this syntax: `intl.formatMessage({ ...messages.myMessage })` but I have to change it to: `intl.formatMessage(messages.myMessage)` to make it work.

**What is the expected behavior?:**
The build work work with no error. 

**Suggested solution:**

**Comment by akameco** [comment]
If it works well in the development environment, it is not a bug in this plugin. Review the babelrc settings.
