### ISSUE TITLE
Usage with gatsby-plugin-intl is not working 

### ISSUE THREAD

**Issue by saschametz** [akameco/babel-plugin-react-intl-auto#74]
I want to use this package together with `gatsby-plugin-intl`

By using `gatsby-plugin-intl` I always need to make my imports from this plugin.

```
import { injectIntl } from "gatsby-plugin-intl";
``` 
instead of
```
import { injectIntl } from "react-intl";
```

Unfortunately this breaks the auto generation of the IDs and I'm getting the error:
```
[React Intl] An `id` must be provided to format a message.
```

I fixed this by importing something from the "react-intl" package even if I don't use it in my component.
```
import { useIntl } from "react-intl";
```

This way it works but I wonder if there is a better solution how I can fix this?

**Comment by akameco** [comment]
@saschametz Please upgrade to v2.3.0. Then add the following to `.babelrc`

```json
{
  "plugins": [
    [
      "react-intl-auto",
      {
        "moduleSourceName": "gatsby-plugin-intl"
      }
    ]
  ]
}
```

**Comment by saschametz** [comment]
@akameco It's working now. Thank you very much
