### ISSUE TITLE
[feature] support `require()` statements

### ISSUE THREAD

**Issue by rapka** [akameco/babel-plugin-react-intl-auto#76]
- `node` version: 10.15.3
- `npm` (or `yarn`) version: 6.4.1

**Do you want to request a _feature_ or report a _bug_?:**
Feature

**What is the current/expected behavior?:**
Hi, sorry for opening another issue in such a short amount of time!

I have an issue that currently requires me to run `extract-react-intl-messages` on files that aren't usually run through Babel. As such, they're currently using `defineMessages`, but because `react-intl` is being imported using `require()` rather than `import`, the strings don't get exported. 

Would adding support for detecting `react-intl` being imported with `require()` be outside of the project scope? I'm also unable to upgrade the project in question to Node 12 at the moment due to dependency issues. I would be happy to help contributing, but my experience of working with Babel is very limited.

**Comment by akameco** [comment]
@rapka I'm sorry. that is difficult. Because even https://github.com/formatjs/formatjs/tree/master/packages/babel-plugin-react-intl is not supported. Please use babel 😿
