### ISSUE TITLE
Add useKey support to intl.formatMessage

### ISSUE THREAD

**Issue by fsmaia** [akameco/babel-plugin-react-intl-auto#82]
* version: 2.3.0
* `node` version: 10.16.1
* `npm` (or `yarn`) version: 6.9.0

**Do you want to request a _feature_ or report a _bug_?:**
Feature

**What is the current behavior?:**
`key` prop is supported only in `<FormattedMessage />` and `<FormattedHTMLMessage />` when using `useKey` option

**What is the expected behavior?:**
`key` property could be supported in `formatMessage` too, e.g.:
```
props.intl.formatMessage({
  key: 'key'
});
```

**Suggested solution:**
Update `addIdToFormatMessage` visitor to support `key` property nodePath.

**Comment by P1X3L** [comment]
I have the exact same issue!

**Comment by akameco** [comment]
Done ✅ Install the latest version 🚀
