### ISSUE TITLE
defineMessages does not handle number as keys

### ISSUE THREAD

**Issue by lcospain** [akameco/babel-plugin-react-intl-auto#96]
* version: 3.0.0
* `node` version: 11.15.0
* `yarn` version: 1.21.1

**Do you want to request a _feature_ or report a _bug_?:** A bug

**What is the current behavior?:**
Trying to extract messages which keys are defined as numbers result in an error being thrown :
`requires Object key or string literal` at the `getId` function
```js
import { defineMessages } from 'react-intl';

export default defineMessages({
  1000: 'foobar'
});
```

**What is the expected behavior?:**
Number keys should be treated as string literals

**Comment by akameco** [comment]
Due to restrictions in react-intl, it must be a string, not a number.

https://github.com/formatjs/react-intl/blob/master/docs/Components.md#message-descriptor
